image: marthydavid/ansible_lint:centos7
test:
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check