---
# tasks file for common
- include_tasks: "{{ansible_distribution}}".yml

- name: install docker-ce
  yum:
    name: docker-ce
    state: present
  notify:
    - start docker    
  register: docker_ce_installed

- name: add docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    name: "{{ docker_users }}"
    groups: docker
    append: yes

- name: add bash_completion package
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ yum_bash_completion }}"

- name: add bash completion
  get_url: 
    url: '{{ bash_completion }}'
    dest: /etc/bash_completion.d/docker
    mode: 0644

- meta: flush_handlers