- name: install epel release
  yum: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ yum_epel_release }}"

- name: install stuff
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ prerequisite_for_repo }}"

- name: configure repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo