- include_vars: "{{ansible_os_family}}.yml"

- name: install epel release
  yum: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ yum_epel_release }}"
  when: ansible_distribution == "CentOS"


- name: install prereqs for CentOS
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ prereq_for_CentOS }}"
  when: ansible_distribution == "CentOS"

- name: install prereqs for Fedora
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ prereq_for_Fedora }}"
  when: ansible_distribution == "Fedora"

- name: Repo installed allready?
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: repo

- name: configure repo for CentOS
  become: true
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == "CentOS" and not repo.stat.exists 

- name: configure repo for Fedora
  become: true
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  when: ansible_distribution == "Fedora" and not repo.stat.exsits

- name: add bash_completion package
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ yum_bash_completion }}"
  when: ansible_distribution == "CentOS"
